# Generated by Django 2.0.5 on 2018-05-25 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('SERVICE', 'Service Request'), ('OTHER', 'Other')], max_length=7)),
                ('domain', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=7)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER CONSIDERATION', 'Under Consideration'), ('NOT CONSIDERED', "Won't Consider"), ('BEING DESIGNED', 'Being Designed'), ('FAILED FEASIBILITY TESTING', 'Failed Feasibility Testing'), ('RESOLVED', 'Resolved')], default='RECEIVED', max_length=26)),
                ('solved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
