# Generated by Django 2.0.5 on 2018-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Service Request', 'Service Request'), ('Other', 'Other')], max_length=7),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='domain',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Under Consideration', 'Under Consideration'), ("Won't consider", "Won't Consider"), ('Being Designed', 'Being Designed'), ('Failed Feasibility Testing', 'Failed Feasibility Testing'), ('Resolved', 'Resolved')], default='RECEIVED', max_length=26),
        ),
    ]
